# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Setup SSH agent
#         uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

#       - name: Deploy Flask App
#         run: |
#           ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
#             cd /home/ec2-user/wordpress-extra
#             git pull
#             sudo pip3 install -r requirements.txt
#             sudo pkill -f "python3 app.py" || true
#             nohup python3 app.py > app.log 2>&1 &

#             sleep 10

#             PORT=$(grep "Running on http://127.0.0.1" app.log | awk -F: '{print $3}')
#             echo "Flask started on port: $PORT"
#             sudo tee /etc/nginx/conf.d/flask.conf <<EOCONF
#                 server {
#                     listen 80;
#                     server_name _;
#                     location / {
#                         proxy_pass http://127.0.0.1:$PORT;
#                     }
#                 }
#           EOCONF

#                 sudo systemctl reload nginx
#           EOF


name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Get EC2 Private IP
        id: get_ip
        run: |
          PRIVATE_IP=$(aws ec2 describe-instances \
            --region us-east-1 \
            --filters "Name=tag:Name,Values=Saad-App-ec2" \
            --query "Reservations[*].Instances[*].PrivateIpAddress" \
            --output text)

          sleep 10

          echo PRIVATE_IP=$PRIVATE_IP

      - name: Deploy Flask App via Bastion
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p ec2-user@${{ secrets.BASTION_HOST }}" \
              ec2-user@$PRIVATE_IP << 'EOF'

            ls

            cd /home/ec2-user/wordpress-extra
            git pull
            sudo pip3 install -r requirements.txt
            sudo pkill -f "python3 app.py" || true

            pwd

            sleep 10

            nohup python3 app.py > /home/ec2-user/app.log 2>&1 &

          EOF





#          #   sleep 10

          #   nohup python3 app.py > /home/ec2-user/app.log 2>&1 &

          #   sleep 10

          #   PORT=$(grep "Running on http://127.0.0.1" /home/ec2-user/app.log | awk -F: '{print $3}')
          #   echo "Flask started on port: $PORT"

          #   sudo tee /etc/nginx/conf.d/flask.conf <<EOCONF
          #   server {
          #       listen 80;
          #       server_name _;
          #       location / {
          #           proxy_pass http://127.0.0.1:$PORT;
          #       }
          #   }
          # EOCONF

          #   sudo systemctl reload nginx